### ISSUE TITLE
Sunshine failed to build, M1 MacBook Pro

### ISSUE THREAD

**Issue by ArcusMG** [LizardByte/homebrew-homebrew#16]
### Describe the Bug

I'm running Mac OS Sonoma, 14.5 (23F79). I have a M1 MacBook Pro. 

I was able to sucsefully add the LizardByte/homebrew repo and start the install. However, I got an error that it failed to build, saying that: 

"symbol(s) not found for architecture arm64"

I've included the make log that has the error in it. Please let me know if there's anything else you need. 
[02.make.txt](https://github.com/user-attachments/files/15508631/02.make.txt)

### Expected Behavior

I had of course expected it to build successfully.

**Comment by ReenigneArcher** [comment]
Please open an issue in Sunshine.
