### ISSUE TITLE
homebrew tap repo name issue

### ISSUE THREAD

**Issue by notch1p** [LizardByte/homebrew-homebrew#5]
### Describe the Bug
```bash
brew tap LizardByte/homebrew
```
According to [homebrew documentation](https://docs.brew.sh/Taps), any homebrew tap repo should start with `homebrew-*`.
The `brew tap` operation will pull from `https://github.com/LizardByte/homebrew-homebrew/` which of course isn't the right url. So we probably have to change the repo name to fit the requirement. e.g. change to homebrew-sunshine
Another solution is to explictly provide the full url like
```
brew tap LizardByte/homebrew https://github.com/LizardByte/homebrew
```
But it's not commonly used.

For reference the homebrew error log:
```
$ brew tap LizardByte/homebrew
==> Tapping lizardbyte/homebrew
Cloning into '/opt/homebrew/Library/Taps/lizardbyte/homebrew-homebrew'...
remote: Repository not found.
fatal: repository 'https://github.com/LizardByte/homebrew-homebrew/' not found
Error: Failure while executing; `git clone https://github.com/LizardByte/homebrew-homebrew /opt/homebrew/Library/Taps/lizardbyte/homebrew-homebrew --origin=origin --template= --config core.fsmonitor=false` exited with 128.
```
Also very glad that sunshine released its own homebrew formula. 👍🏻

**Comment by ReenigneArcher** [comment]
Thanks for opening this issue.

`homebrew-sunshine` is not ideal since this repo may possibly hold other LizardByte apps in the future.

I guess `homebrew-homebrew` is the easiest, although it's a bit weird to name a repo like that... but I decided to go with that since it wouldn't require any documentation changes.
